//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Security.Cryptography;
using System.IO;
using System.Xml;
using System.Threading.Tasks;

public class Torrent
{
    private Torrent()
    {
        Clients = new List<Client>();
        id = "";
        Random r = new Random();
        byte[] bytes = new byte[16];
        for (int i = 0; i < 16; ++i)
            bytes[i] = (byte)r.Next(256);
        id = hashToString(bytes);
    }

    private Torrent(string id)
    {
        Clients = new List<Client>();
        this.id = id;
    }

    public enum eStatus
    {
        Downloading,
        Paused,
        Stopped,
        Seeding
    }

    internal void AddClient(Client mc)
    {
        Clients.Add(mc);
        mc.Listen();
    }

    

    public virtual eStatus Status
	{
		get;
		set;
	}

	public virtual object DownloadSpeed
	{
		get;
	}


    private readonly string id;
    public  string Id
    {
        get { return id;}
    }

	public virtual object UploadSpeed
	{
		get;
	}

	public virtual string FilePath
	{
		get;
		private set;
	}
    public virtual string FileName
    {
        get;
        private set;
    }


    public virtual object ProgressOfFile
	{
		get;
	}

	public virtual List<Client> Clients
	{
		get;
		set;
	}

    public PartFile File;
    public long Size
    {
        get { return File.Size; }
    }
    
    public string Name { get; set; }
    public static string XmlName = "torrent";

    public XmlElement SaveToXml(XmlDocument doc)
    {
        XmlElement e = doc.CreateElement(XmlName);

        e.AppendElementWithValue("name", Name);
        e.AppendElementWithValue("id", Id);
        e.AppendElementWithValue("status", Status.ToString());
        e.AppendChild(File.SaveToXml(doc));

        return e;
    }

    internal async Task Download()
    {
        Status = Torrent.eStatus.Downloading;
        Logger.WriteLine("Starting download:" + Name);

        
        
    }

    private static string hashToString(byte[] hash)
    {
        return BitConverter.ToString(hash).Replace("-", string.Empty);
    }


	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Pause()
	{
		throw new System.NotImplementedException();
	}

    public static Torrent CreateFromPath(string path)
    {
        Torrent t = new Torrent();
        t.FilePath = path;
        
        
        t.Name = t.FileName;
        t.Status = eStatus.Seeding;
        return t;
    }

    public static Torrent CreateFromXml(XmlElement elem)
    {
        return CreateFromXml(elem, elem["filepath"].InnerText);

        
    }

    public static Torrent CreateFromXml(XmlElement elem, string filePath)
    {
        Torrent t = new Torrent(elem["id"].InnerText);
        t.Name = elem["name"].InnerText;
        t.FileName = elem["filename"].InnerText;
        t.FilePath = filePath;
        
        t.Size = int.Parse(elem["size"].InnerText);
        t.Status = (eStatus) Enum.Parse(typeof(eStatus), elem["status"].InnerText);
        return t;
    }

}



