//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Torrent
{
	public virtual object Status
	{
		get;
		set;
	}

	public virtual object DownloadSpeed
	{
		get;
		set;
	}

	public virtual object UploadSpeed
	{
		get;
		set;
	}

	public virtual string File
	{
		get;
		set;
	}

	public virtual object ProgressOfFile
	{
		get;
		set;
	}

	public virtual object Clients
	{
		get;
		set;
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Pause()
	{
		throw new System.NotImplementedException();
	}

}

